channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=22.3.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.3.1
  - psutil==5.9.8
  - pyyaml==6.0.2
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env
