name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: python train.py
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
    
    - name: Build Docker image
      run: docker build -t crop-recommendation-service:${{ github.sha }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker tag crop-recommendation-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/crop-recommendation-service:${{ github.sha }}
        docker tag crop-recommendation-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/crop-recommendation-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/crop-recommendation-service:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/crop-recommendation-service:latest